HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<!DOCTYPE html>
<html>
<head>
	<title>Oops :(</title>
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
	<style>
	* {
		font-family: 'Montserrat', sans-serif;
		color: #FFFFFF;
	}
	body {
		text-align: center;
		background-color: #9E1B34;
	}
	img#logo {
		height: 75px;
		width: 75px;
	}
	</style>
</head>
<body>
	<h2>TEMPLE ACM</h2>
	<br>
	<br>
	<h3>Oops :(</h3>
	<p>We are currently experiencing difficulties, please come back soon!</p>
</body>
</html>
